import type { RenderStyle } from "./render-style";

export type ExportPreset = "default-doc" | "sop" | "share-article";

export type ExportPresetOption = {
  value: ExportPreset;
  label: string;
  shortLabel: string;
  description: string;
  renderStyle: RenderStyle;
  showToc: boolean;
  showTitleBlock: boolean;
  titleBlockEyebrow: string;
  titleBlockDescription: string;
  headerText: string | null;
  footerText: string | null;
};

export const EXPORT_PRESET_OPTIONS: ExportPresetOption[] = [
  {
    value: "default-doc",
    label: "默认文档",
    shortLabel: "文档",
    description: "平衡预览与导出，适合通用说明与技术文档。",
    renderStyle: "default",
    showToc: true,
    showTitleBlock: true,
    titleBlockEyebrow: "交付文档",
    titleBlockDescription: "适合通用说明、方案与技术文档，兼顾结构表达与阅读体验。",
    headerText: "mdshare · 默认文档",
    footerText: "Generated by mdshare",
  },
  {
    value: "sop",
    label: "流程 SOP",
    shortLabel: "SOP",
    description: "结构更紧凑，适合步骤说明、流程清单与交付手册。",
    renderStyle: "compact",
    showToc: true,
    showTitleBlock: false,
    titleBlockEyebrow: "流程 SOP",
    titleBlockDescription: "用于步骤说明、执行流程与交付手册，强调清晰的操作上下文。",
    headerText: null,
    footerText: null,
  },
  {
    value: "share-article",
    label: "分享长文",
    shortLabel: "长文",
    description: "阅读优先，默认隐藏目录，更适合外部分享与文章导出。",
    renderStyle: "article",
    showToc: false,
    showTitleBlock: true,
    titleBlockEyebrow: "分享长文",
    titleBlockDescription: "面向阅读与外部分享，保持更轻的版式负担与更聚焦的内容呈现。",
    headerText: null,
    footerText: "Published with mdshare",
  },
];

export function isExportPreset(value: string | null | undefined): value is ExportPreset {
  return value === "default-doc" || value === "sop" || value === "share-article";
}

export function getExportPreset(value: ExportPreset) {
  return EXPORT_PRESET_OPTIONS.find((option) => option.value === value) ?? EXPORT_PRESET_OPTIONS[0];
}

export function mapRenderStyleToExportPreset(renderStyle: RenderStyle): ExportPreset {
  switch (renderStyle) {
    case "compact":
      return "sop";
    case "article":
      return "share-article";
    default:
      return "default-doc";
  }
}
