import { describe, expect, it } from "vitest";
import { buildExportHtml } from "../../src/lib/markdown/template";

describe("export template", () => {
  it("includes inline code and fenced code styles", () => {
    const html = buildExportHtml({
      title: "demo",
      theme: "light",
      exportPreset: "default-doc",
      toc: [{ id: "section", text: "Section", level: 2, line: 3 }],
      html: '<h2 id="section">Section</h2><p>inline <code>value</code></p><pre class="hljs"><code class="language-ts"><span class="hljs-keyword">const</span> value = 1;</code></pre>',
    });

    expect(html).toContain('<article class="export-body">');
    expect(html).toContain('<header class="export-header">mdshare · 默认文档</header>');
    expect(html).toContain('<section class="export-title-block">');
    expect(html).toContain('Generated by mdshare');
    expect(html).toContain('--bg: #f8fafc;');
    expect(html).toContain('--panel: #ffffff;');
    expect(html).toContain('--accent-soft: rgba(37, 99, 235, 0.12);');
    expect(html).toContain('--shadow: 0 10px 30px rgba(15, 23, 42, 0.08);');
    expect(html).toContain('.export-body :not(pre) > code');
    expect(html).toContain('.export-body .hljs-keyword');
    expect(html).toContain('.export-body a:hover');
    expect(html).toContain('text-underline-offset: 0.18em;');
    expect(html).toContain('.export-body pre.hljs[data-language]::before');
    expect(html).toContain('.export-body pre.hljs[data-language="shell"]');
    expect(html).toContain('.export-body pre.hljs[data-language="yaml"]');
    expect(html).toContain('.export-body pre.hljs[data-language="javascript"]');
    expect(html).toContain('.export-body pre.hljs[data-language="java"]');
    expect(html).toContain('.export-body pre.hljs[data-language="text"]');
    expect(html).toContain('.export-body pre.hljs[data-language="python"]');
    expect(html).toContain('.export-body pre.hljs[data-language="sql"]');
    expect(html).toContain('.export-body pre.hljs[data-language="json"]');
    expect(html).toContain('.export-body pre.hljs[data-language="rust"]');
    expect(html).toContain('.export-body pre.hljs[data-language="go"]');
    expect(html).toContain('.export-body pre.hljs[data-language="dockerfile"]');
    expect(html).toContain('.export-body pre.hljs[data-language="vue"]');
    expect(html).toContain('page--with-toc');
  });

  it("anchors exported code language badges inside code blocks", () => {
    const html = buildExportHtml({
      title: "demo",
      theme: "light",
      exportPreset: "default-doc",
      toc: [],
      html: '<pre class="hljs" data-language="javascript" data-language-label="JavaScript"><code class="language-javascript">console.log(1)</code></pre>',
    });

    expect(html).toContain('.export-body pre.hljs[data-language] {');
    expect(html).toContain('position: relative;');
    expect(html).toContain('padding-top: 52px;');
  });

  it("includes responsive image and narrow-screen styles", () => {
    const html = buildExportHtml({
      title: "demo",
      theme: "light",
      exportPreset: "share-article",
      toc: [],
      html: '<p><img src="./demo.png" alt="demo"></p>',
    });

    expect(html).toContain('.export-body img {');
    expect(html).toContain('max-width: 100%');
    expect(html).toContain('height: auto;');
    expect(html).toContain('border-radius: var(--mdshare-image-radius, 16px)');
    expect(html).toContain('box-shadow: var(--mdshare-image-shadow, var(--shadow));');
    expect(html).toContain('page--without-toc');
    expect(html).toContain('@media (max-width: 900px)');
    expect(html).toContain('grid-template-columns: 1fr');
    expect(html).not.toContain('<header class="export-header">');
    expect(html).toContain('Published with mdshare');
  });

  it("can hide toc even when headings exist", () => {
    const html = buildExportHtml({
      title: "demo",
      theme: "light",
      exportPreset: "share-article",
      toc: [{ id: "section", text: "Section", level: 2, line: 1 }],
      html: '<h2 id="section">Section</h2>',
    });

    expect(html).toContain('page--without-toc');
    expect(html).not.toContain('<aside class="export-toc">');
  });

  it("hides sop chrome copy from exported body header area", () => {
    const html = buildExportHtml({
      title: "运行手册",
      theme: "light",
      exportPreset: "sop",
      toc: [],
      html: '<p>step by step</p>',
    });

    expect(html).not.toContain('标准操作流程');
    expect(html).not.toContain('流程 SOP');
    expect(html).not.toContain('<section class="export-title-block">');
    expect(html).not.toContain('<header class="export-header">');
  });

  it("includes mermaid preview styles", () => {
    const html = buildExportHtml({
      title: "demo",
      theme: "light",
      exportPreset: "default-doc",
      toc: [],
      html: '<div class="mermaid-preview"><div class="mermaid-preview__diagram"><svg></svg></div></div>',
    });

    expect(html).toContain('.export-body .mermaid-preview');
    expect(html).toContain('background: linear-gradient(180deg, var(--panel) 0%, var(--accent-soft) 100%);');
    expect(html).toContain('.export-body .mermaid-preview svg');
    expect(html).toContain('width: 100% !important');
    expect(html).toContain('.export-body .mermaid-preview__error-title');
    expect(html).toContain('html[data-theme="dark"] .export-body .mermaid-preview__error');
    expect(html).toContain('.export-body .mermaid-preview[data-mermaid-state="error"]');
  });

  it("includes callout styles for supported alert types", () => {
    const html = buildExportHtml({
      title: "demo",
      theme: "light",
      exportPreset: "default-doc",
      toc: [],
      html: '<blockquote class="callout callout--tip"><p class="callout__title">TIP</p><p>hello</p></blockquote>',
    });

    expect(html).toContain('.export-body .callout {');
    expect(html).toContain('.export-body .callout__title {');
    expect(html).toContain('.export-body .callout--tip {');
    expect(html).toContain('.export-body .callout--note {');
    expect(html).toContain('.export-body .callout--warning {');
    expect(html).toContain('.export-body .callout--important {');
    expect(html).toContain('.export-body .callout--caution {');
  });
});
